/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Vista;

import com.mycompany.Controlador.RequerimientoControlador;
import com.mycompany.Modelo.Vo.Consulta1Vo;
import com.mycompany.Modelo.Vo.Consulta2Vo;
import com.mycompany.Modelo.Vo.Consulta3Vo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria camila
 */
public class FrmRequerimientos extends javax.swing.JFrame {

	/**
	 * Creates new form FrmRequerimientos
	 */
	public FrmRequerimientos() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnRequerimiento1 = new javax.swing.JButton();
                btnRequerimiento2 = new javax.swing.JButton();
                btnRequerimiento3 = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                miTabla = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnRequerimiento1.setBackground(new java.awt.Color(153, 153, 255));
                btnRequerimiento1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnRequerimiento1.setText("Informe1");
                btnRequerimiento1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRequerimiento1ActionPerformed(evt);
                        }
                });

                btnRequerimiento2.setBackground(new java.awt.Color(153, 153, 255));
                btnRequerimiento2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnRequerimiento2.setText("Informe2");
                btnRequerimiento2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRequerimiento2ActionPerformed(evt);
                        }
                });

                btnRequerimiento3.setBackground(new java.awt.Color(153, 153, 255));
                btnRequerimiento3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnRequerimiento3.setText("Informe3");
                btnRequerimiento3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRequerimiento3ActionPerformed(evt);
                        }
                });

                miTabla.setBackground(new java.awt.Color(204, 255, 255));
                miTabla.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {

                        }
                ));
                jScrollPane1.setViewportView(miTabla);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnRequerimiento1)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRequerimiento2)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRequerimiento3))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(27, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRequerimiento1)
                                        .addComponent(btnRequerimiento3)
                                        .addComponent(btnRequerimiento2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnRequerimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimiento1ActionPerformed
                // TODO add your handling code here:
		String[] columnNombre = {"Id_Lider", "Nombre", "Primer_Apellido", "Ciudad_Residencia"};
	    RequerimientoControlador controlador = new RequerimientoControlador();
	    
	    ArrayList<Consulta1Vo> listaA;
	    
	       try {
	       listaA = controlador.consultarAsesorPorCiudad();
	   
	       Object[][] datos = new Object[listaA.size()][4];
	       int index = 0;
	       
	       for (Consulta1Vo lista: listaA){
		   datos[index][0] = lista.getId_Lider();
		   datos[index][1] = lista.getNombre();
		   datos[index][2] = lista.getPrimer_Apellido();
		   datos[index][3] = lista.getCiudad_Residencia();
		   index++;
	       }
	   
	       
	      DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
	      miTabla.setModel(model);
	         
	                	           
	   }catch (SQLException e){
	      System.err.println(e.getMessage());
	   }

	    
	    
                            
        }//GEN-LAST:event_btnRequerimiento1ActionPerformed

        private void btnRequerimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimiento2ActionPerformed
                // TODO add your handling code here:
          String[] columnNombre = {"ID_Proyecto", "Constructora","Numero_Habitaciones", "Ciudad"};
	    RequerimientoControlador controlador = new RequerimientoControlador();
	    
	    ArrayList<Consulta2Vo> listaA;
	    
	       try {
	       listaA = controlador.consultarProyectoCasaCampestre();
	   
	       Object[][] datos = new Object[listaA.size()][4];
	       int index = 0;
	       
	       for (Consulta2Vo lista: listaA){
		   datos[index][0] = lista.getID_Proyecto();
		   datos[index][1] = lista.getConstructora();
		   datos[index][2] = lista.getNumero_Habitaciones();
		   datos[index][3] = lista.getCiudad();
		   index++;
	       }
	   
	       
	      DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
	      miTabla.setModel(model);
	         
	                	           
	   }catch (SQLException e){
	      System.err.println(e.getMessage());
	   }

			
        }//GEN-LAST:event_btnRequerimiento2ActionPerformed

        private void btnRequerimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimiento3ActionPerformed
                // TODO add your handling code here:
	  String[] columnNombre = {"ID_Compra", "Constructora", "Banco_Vinculado"};
	    RequerimientoControlador controlador = new RequerimientoControlador();
	    
	    ArrayList<Consulta3Vo> listaA;
	    
	       try {
	       listaA = controlador.consultarCompraPorProveedor();
	   
	       Object[][] datos = new Object[listaA.size()][3];
	       int index = 0;
	       
	       for (Consulta3Vo lista: listaA){
		   datos[index][0] = lista.getID_Compra();
		   datos[index][1] = lista.getConstructora();
		   datos[index][2] = lista.getBanco_Vinculado();
		   index++;
	       }
	   
	       
	      DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
	      miTabla.setModel(model);
	         
	                	           
	   }catch (SQLException e){
	      System.err.println(e.getMessage());
	   }

		
		
		
        }//GEN-LAST:event_btnRequerimiento3ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FrmRequerimientos().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnRequerimiento1;
        private javax.swing.JButton btnRequerimiento2;
        private javax.swing.JButton btnRequerimiento3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable miTabla;
        // End of variables declaration//GEN-END:variables
}
